name: Continuous integration
on:
  push:
    branches:
      - master
  pull_request:
  merge_group:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        rust_channel:
          - stable
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: macos-latest
            system: x86_64-darwin
            continue-on-error: true

    runs-on: ${{ matrix.os }}
    # The `== true` makes it work wether continue-on-error has been defined or not.
    continue-on-error: ${{ matrix.continue-on-error == true }}

    steps:

    - name: Checking out the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Installing Nix
      uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          accept-flake-config = true

    - name: Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Run all checks
      run: |
        nix flake check --print-build-logs
