jobs:
  build-and-test-linux:
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
    - name: Checking out the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Installing Nix
      uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |-
          experimental-features = nix-command flakes
          accept-flake-config = true
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Run all checks
      run: nix flake check --print-build-logs
  build-and-test-macos:
    continue-on-error: true
    runs-on: macos-latest
    steps:
    - name: Checking out the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Installing Nix
      uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |-
          experimental-features = nix-command flakes
          accept-flake-config = true
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Run all checks
      run: nix flake check --print-build-logs
name: Continuous integration
on:
  merge_group: {}
  pull_request: {}
  push:
    branches:
    - master
